

service: design-service

plugins:
  - serverless-pseudo-parameters
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ca-central-1
  iamRoleStatements:
    - ${file(iam/designsTableIAM.yml):designsTableIAM}
  
resources:
  Resources:
    designsBucket: ${file(resources/designsBucket.yml):designsBucket}
    designsBucketPolicy: ${file(resources/designsBucket.yml):designsBucketPolicy}
    designsTable: ${file(resources/designsTable.yml):designsTable}


functions:
  getDesigns:
    handler: src/getDesigns.handler
    events: 
      - http:
          method: GET
          path: /designs

custom:
  designsBucket:
    name: designs-bucket-#{AWS::AccountId}-${self:provider.stage}
