designsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: designsTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
    KeySchema:
      - AttributeName: id
        KeyType: HASH